### PR TITLE
Search (and more)

### PR DESCRIPTION
**Pull request by agritter**
- Add search. I moved it down because there wasn't really room in the header and I was thinking we could later put the site selection in the header
- Respond to Matthew's comments:
- I ended up just increasing the room for the units. I'm not sure if that is what we want in the end, but I think the textboxes look awkwardly big without them and at least on my screen there is now enough room for a reasonably long item name
- Make the edit/delete show up immediately in the list view

### CODE REVIEW

**Review by MatthewWalstra — APPROVED** [review]
Everything looks very nice and works well, except for the item edit + and - buttons still look shifted down and to the right. I don't know what fixes that because the style has them center aligned vertically and horizontally. I think we leave it and fix it later if we have time.

**Comment by agritter** [comment]
> Everything looks very nice and works well, except for the item edit + and - buttons still look shifted down and to the right. I don't know what fixes that because the style has them center aligned vertically and horizontally. I think we leave it and fix it later if we have time.

Hmm... it looks centered on my phone so I'm guessing it is to do with the screen size (i.e. icons are bigger than circle for smaller screen). I'll make the button size not a % in a future PR and I think that'll fix it.

**Comment by MatthewWalstra** [comment]
image

**Comment by MatthewWalstra** [comment]
I think if you make the button a percent, the icon also has to be a percent, so they scale together.

**Comment by agritter** [comment]
Yeah, that does look bad.  The icon's size is defined as a prop of the component rather than the style, so I'm not sure if it can be set to a %. But either way we should probably make them both percent or both absolute.

**Pull request merged**
