### PR TITLE
Close modal (trailer/sort pickers) when background is tapped

### PR DESCRIPTION
**Pull request by agritter**

### CODE REVIEW

**Review by MatthewWalstra — COMMENTED** [review]
Clicking inside the modal (next to a name, but not on it) closes the box. Is that the desired behavior?

**Comment by agritter** [comment]
No, good catch. The way it was you could miss clicking a name and think you hit it. 
I made changes.

**Review by MatthewWalstra — APPROVED** [review]
Works well.

**Review by aez9 — COMMENTED** [review]
Looks good

**Pull request merged**
